import 'bootstrap';
import './common/click-actions';
import './common/lazy-load-img';
import './entity/awake-times';
import './entity/birthdays';
import './entity/autocomplete';
import './entity/list-image-gen';
import './entity/list-search';
import Browser from './entity/browser.js';
import TownBrowser from './towns/town-browser.js';